CREATE TABLE IF NOT EXISTS friends (
	FriendID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES users(UserID) ON DELETE CASCADE,
    FriendUserID INTEGER REFERENCES users(UserID) ON DELETE CASCADE,
	FriendStatus BOOLEAN DEFAULT 'PENDING',
	CreatedAt TIMESTAMP DEFAULT NOW()
);