CREATE TABLE IF NOT EXISTS posts (
	PostID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES users(UserID) ON DELETE CASCADE,
	Content TEXT NOT NULL,
	Mood VARCHAR(50) DEFAULT 'NORMAL',
	CreatedAt TIMESTAMP DEFAULT NOW()
);