CREATE TABLE IF NOT EXISTS comments (
	CommentID SERIAL PRIMARY KEY,
	PostID INTEGER REFERENCES posts(PostID) ON DELETE CASCADE,
	UserID INTEGER REFERENCES users(UserID) ON DELETE CASCADE,
    Content TEXT NOT NULL,
	CreatedAt TIMESTAMP DEFAULT NOW()
);