name: Deploy Mood Bridge v2 Backend

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t admantix/mood-bridge-v2-backend:latest .

      - name: Push Image to Docker Hub
        run: docker push admantix/mood-bridge-v2-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Latest Image
        run: docker pull admantix/mood-bridge-v2-backend:latest

      - name: Remove Old Container
        run: |
          docker stop go-app-container || true
          docker rm go-app-container || true

      - name: Create .env File in server/
        run: |
          mkdir -p server
          cat <<EOF > server/.env
PORT=${{ secrets.PORT }}
DBNAME=${{ secrets.DBNAME }}
HOST=${{ secrets.HOST }}
USER=${{ secrets.USER }}
PASSWORD=${{ secrets.PASSWORD }}
JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}
JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
MIC_PREDICT_URL=${{ secrets.MIC_PREDICT_URL }}
MIC_PREDICT_MANY_URL=${{ secrets.MIC_PREDICT_MANY_URL }}
REDIS_ADDR=${{ secrets.REDIS_ADDR }}
REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
EOF

      - name: Run New Container using .env
        run: |
          docker run -d \
            --name go-app-container \
            --env-file server/.env \
            -p 8080:8080 \
            admantix/mood-bridge-v2-backend:latest

      - name: Clean Up .env File
        run: rm server/.env
