name: Deploy Mood Bridge v2 Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t admantix/mood-bridge-v2-backend .

      - name: Push Image to Docker Hub
        run: docker push admantix/mood-bridge-v2-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull admantix/mood-bridge-v2-backend:latest

      - name: Stop and Remove Existing Container (if exists)
        run: |
          docker rm -f go-app-container || true

      - name: Run New Docker Container
        run: |
          docker run -d -p 8080:8080 \
            --name go-app-container \
            -e PORT=${{ secrets.PORT }} \
            -e DBNAME=${{ secrets.DBNAME }} \
            -e HOST=${{ secrets.HOST }} \
            -e JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e MIC_PREDICT_URL=${{ secrets.MIC_PREDICT_URL }} \
            -e MIC_PREDICT_MANY_URL=${{ secrets.MIC_PREDICT_MANY_URL }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            -e REDIS_URL=${{ secrets.REDIS_URL }} \
            -e USER=${{ secrets.USER }} \
            admantix/mood-bridge-v2-backend:latest
