name: Deploy Mood Bridge v2 Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DBNAME=${{ secrets.DBNAME }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "MIC_PREDICT_URL=${{ secrets.MIC_PREDICT_URL }}" >> .env
          echo "MIC_PREDICT_MANY_URL=${{ secrets.MIC_PREDICT_MANY_URL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "USER=${{ secrets.USER }}" >> .env

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t admantix/mood-bridge-v2-backend .

      - name: Push image to Docker Hub
        run: docker push admantix/mood-bridge-v2-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull admantix/mood-bridge-v2-backend:latest

      - name: Delete Docker container if exists
        run: docker rm -f go-app-container || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name go-app-container \
            -p 8080:8080 \
            --env-file .env \
            admantix/mood-bridge-v2-backend:latest
