name: Deploy Mood Bridge v2 Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t admantix/mood-bridge-v2-backend:latest .

      - name: Push Image to Docker Hub
        run: docker push admantix/mood-bridge-v2-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Latest Image
        run: docker pull admantix/mood-bridge-v2-backend:latest

      - name: Remove Old Container
        run: |
          docker stop go-app-container || true
          docker rm go-app-container || true

      - name: Run New Container
        run: |
          docker run -d \
            --name go-app-container \
            -p 8080:8080 \
            -e PORT=${{ secrets.PORT }} \
            -e DBNAME=${{ secrets.DBNAME }} \
            -e HOST=${{ secrets.HOST }} \
            -e USER=${{ secrets.USER }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            -e JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e MIC_PREDICT_URL=${{ secrets.MIC_PREDICT_URL }} \
            -e MIC_PREDICT_MANY_URL=${{ secrets.MIC_PREDICT_MANY_URL }} \
            -e REDIS_ADDR=${{ secrets.REDIS_ADDR }} \
            -e REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} \
            -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            admantix/mood-bridge-v2-backend:latest
