name: Deploy Mood Bridge v2 Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file for build
        run: |
          mkdir -p server
          echo "PORT=${{ secrets.PORT }}" > server/.env
          echo "DBNAME=${{ secrets.DBNAME }}" >> server/.env
          echo "HOST=${{ secrets.HOST }}" >> server/.env
          echo "USER=${{ secrets.USER }}" >> server/.env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> server/.env
          echo "JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}" >> server/.env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> server/.env
          echo "MIC_PREDICT_URL=${{ secrets.MIC_PREDICT_URL }}" >> server/.env
          echo "MIC_PREDICT_MANY_URL=${{ secrets.MIC_PREDICT_MANY_URL }}" >> server/.env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> server/.env
          echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> server/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> server/.env
          echo "HUGGINGFACE_API_TOKEN=${{ secrets.HUGGINGFACE_API_TOKEN }}" >> server/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: admantix/mood-bridge-v2-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Latest Image from Docker Hub
        run: docker pull admantix/mood-bridge-v2-backend:latest

      - name: Stop and Run New Container
        run: |
          docker rm -f go-app-container || true
          docker run -d \
            --name go-app-container \
            --restart always \
            -p 8080:8080 \
            admantix/mood-bridge-v2-backend:latest
